# Generated by Django 3.1.2 on 2020-11-26 13:38

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields
import product.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=500, unique=True)),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='product.category')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Characteristic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manufacturer', models.CharField(max_length=255)),
                ('weight', models.IntegerField()),
                ('color', models.CharField(max_length=255)),
                ('model', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=255)),
                ('product_description', models.TextField()),
                ('product_price', models.IntegerField()),
                ('product_image', models.FileField(upload_to=product.models.upload_product_img)),
                ('product_count', models.IntegerField()),
                ('product_sale', models.IntegerField()),
                ('is_feachered', models.BooleanField(default=False)),
                ('publish_date', models.DateField()),
                ('slug', models.SlugField(max_length=500)),
                ('categories', mptt.fields.TreeManyToManyField(related_name='products', to='product.Category')),
                ('characteristic', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='product.characteristic')),
            ],
        ),
    ]
