# Generated by Django 3.1.2 on 2020-11-26 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_auto_20201126_1405'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderbasket',
            name='is_order',
            field=models.BooleanField(default=False),
        ),
    ]
