# Generated by Django 3.1.2 on 2020-11-26 14:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_orderbasket_is_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderbasket',
            name='time',
        ),
        migrations.RemoveField(
            model_name='orderbasket',
            name='user',
        ),
        migrations.AddField(
            model_name='order',
            name='total',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orderbasket',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
