# Generated by Django 3.1.2 on 2020-11-26 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basket', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basket',
            name='time',
            field=models.DateTimeField(default=''),
        ),
    ]
